services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: ["gunicorn", "crud_project.wsgi:application", "--bind", "0.0.0.0:8000"] 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # TO DO: Remove from Prod docker-compose file
    env_file: .env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./private.key.pem:/etc/ssl/private/private.key.pem
      - ./domain.cert.pem:/ssl/certs/domain.cert.pem
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
